name: scrape
on: push
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
      - name: scrape the site 🧽
        run: |
          docker run -it algolia/docsearch-scraper:v1.6.0
